---
 - name: showig variables
   hosts: prod
   vars:
      os: "linux"
      cloud: "aws"
      tools: "devops"
   tasks:
      - name: debug message
        debug:
          msg: "i love {{os}}"
      - name: hello
        debug:
         var: cloud
