#!/usr/bin/ansible-playbook
---
 - name: showig variables
   hosts: prod
   tasks:
      - name: server kenel
        command: uname -a
        register: ker
      - debug: var=ker.stdout
        tags: kernel
      - name: server date
        command: date
        register: date
      - debug: var=date.stdout
        tags: date
      - name: server uptime
        tags: up
        command: uptime
        register: up
      - debug: var=up.stdout
      - name: server hostname
        command: hostname
        register: host
      - debug: var=host.stdout
        tags: host
