---
 - hosts: prod
   gather_facts: false
   vars:
     dir_create: /tmp/varains/v1/v2/v3/
     log_file: /var/log/messages
   tasks:
        - name: creating a files
          file:
            state: directory
            recurse: yes
            path: "{{dir_create}}"
        - name: copy file
          copy:
            src: "{{log_file}}"
            dest: "{{dir_create}}"
